"""empty message

Revision ID: 2124bf714ebe
Revises: 36def05afc6e
Create Date: 2025-02-14 23:54:44.614435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2124bf714ebe'
down_revision = '36def05afc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_to_author', schema=None) as batch_op:
        batch_op.drop_constraint('book_to_author_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('book_to_author_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_to_author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_to_author_book_id_fkey', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('book_to_author_author_id_fkey', 'author', ['author_id'], ['id'])

    # ### end Alembic commands ###
