"""empty message

Revision ID: 36def05afc6e
Revises: ef93c5f40477
Create Date: 2025-02-14 23:21:48.127219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36def05afc6e'
down_revision = 'ef93c5f40477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_author',
    sa.Column('use_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['use_id'], ['user.id'], )
    )
    op.create_table('user_to_book',
    sa.Column('use_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['use_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_book')
    op.drop_table('user_to_author')
    # ### end Alembic commands ###
