"""empty message

Revision ID: dc155fb5ae9a
Revises: 2124bf714ebe
Create Date: 2025-02-14 23:56:09.433364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc155fb5ae9a'
down_revision = '2124bf714ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_author', schema=None) as batch_op:
        batch_op.drop_constraint('user_to_author_use_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_to_author_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['use_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_to_book', schema=None) as batch_op:
        batch_op.drop_constraint('user_to_book_use_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_to_book_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'book', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['use_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_to_book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_to_book_book_id_fkey', 'book', ['book_id'], ['id'])
        batch_op.create_foreign_key('user_to_book_use_id_fkey', 'user', ['use_id'], ['id'])

    with op.batch_alter_table('user_to_author', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_to_author_author_id_fkey', 'author', ['author_id'], ['id'])
        batch_op.create_foreign_key('user_to_author_use_id_fkey', 'user', ['use_id'], ['id'])

    # ### end Alembic commands ###
